[package]
name = "csrp_compat"
version = "0.1.0"
edition = "2024"

[dependencies]
openssl-sys = { version = "0.9.110", features = ["vendored"] }
rand = "0.9.2"
sha2 = "0.10.9"
srp = { git = "https://github.com/feliwir/PAKEs.git", rev = "57ab697" }

[build-dependencies]
cc = "1.0"
